# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G -XX:MaxMetaspaceSize=512m
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.19.2
yarn_mappings=1.19.2+build.28
loader_version=0.16.9

# Mod Properties
mod_version=0.2.0
maven_group=io.github.chromonym.exspectriments
archives_base_name=exspectriments

# Dependencies
fabric_version=0.77.0+1.19.2
rei_version=9.2.784
emi_version=1.1.18+1.19.2
architectury_version=6.6.92
modmenu_version=4.1.2
spectrum_version=cZcvzTh4
revelationary_version=2d9fuEjc
cloth_config_version=8.3.134
patchouli_version=1.19.2-77-FABRIC
trinkets_version=3.4.1
matchbooks_version=1.20-SNAPSHOT
fractal_version=8I3R187M
additional_entity_attributes_version=ht3amcX1
cca_version=5.0.2
arrowhead_version=ad8ef53b00
dimensional_reverb_version=0a4cd0ae47
reach_entity_attributes_version=2.3.0
mixin_extras_version=0.1.1
cosmetic_armor_version=vSPCrVPs
roses_thorntilities_version=1pUjseRY
ears_version=1.4.6

# What recipe viewer to use ('emi', 'rei', or 'disabled')
recipe_viewer=emi